name: tutility
publish_to: "none"
version: 1.2.5+15

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  auto_route: ^8.0.3
  crypto: ^3.0.3
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  package_info_plus: ^6.0.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.1
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/get_timetable.js

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon_adaptive.png"
